name: 'taxi_analytics'
version: '1.0.0'
config-version: 2

profile: 'taxi_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  taxi_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

vars:
  data_dir: "{{ env_var('DATA_DIR', 'data') }}"
  curated_trips_glob: "{{ env_var('DATA_DIR', 'data') }}/curated/trips/**/*.parquet"
  zones_csv: "{{ env_var('DATA_DIR', 'data') }}/raw/taxi_zones/taxi_zone_lookup.csv"
